# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gsOua7zhC+YwVnTAmJYpic7SMglH1jHkpTqtcrwN5uztoFYuLBr18s06CEJZmjVqy4mlJV/6yLJy+oGUJxDaM4Vu9daht2B0CukuxerRZNXDUe3Y8PfdQFomT9nhaJS7ca72yW0ecXTObcIuTDPIuec4J70kA3WJCXTgAnpWf3BVA60eYG70SHnxxCGNpWSMLxzbi+SfoMpoXIKxHyJF3SNBNKhxIZHFzIEiRqFcGWPj9vcYJHQvQAvUk6LQ8rNg/01X9pwIyLwrDdRNzI+ZASLyqnZkuTHJPp1a8v/+MsFDvyEK5nXyxs46gqGxYyvQw9/JlfwuPBpfwgTMeXkCkeXBQHP+vZ/IlyWbp0ed2ReLeYb57Jd+mXXb9HeWsxRpaitMs2XHcUvejs58sBr7K3vAUwoj84CIt/KJ8N4Z2+FvCLlyBN0g3Q9V5Lh0NWaK6aRvh+drsHegpsg58rKu61+a+4Yv16is+G+/4HhVaFAuyVjzHnws0sr2Cj8z8l4Y8XV5dwao8CHl3HaRyQtLPOeffSGnpQCWkTaZjAU7n+U+lQT3aP7km/wSsEPieCp3ExcyRXSEAwgXEOTTjf3hWHa42mFlsVtavm8YwqHI3jOs0YJCriySXw9np4RW4+zXSHER4MqGZ/YGUhCf7xqUSWZsqt9SzdPp/eLbFMkL02c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
