travis:
  secure:
    BINSTAR_TOKEN: EB/6qDZNVoISfg77md8SAHimKvJCwZ3R4TRD6H09wJ1/NBCRigwuQl7BwNHLRalzhmE8KdIcrQosg+b7DLIt+YpibjAiWqaUe0cUpy3npftOL5bOv25vrEQIjR4NZcBBOcddzI1q/7EXYfME99oUm1tQX9ltap3+kbBJb/gIeMDHjRZsMRMgl4Jw1hBPicvHNWB/0jGizUETywPawKrbWFCngfJFJdw+j5AJYLBHh9Vm0LIHOenWr120PuN8FOtdWQC1UasLzT6VbS/ScnCbbWie6njTU2sxxnoEgBi914ECPs4c6i41MwvgtnUqiCUiIX8IFp4urokzPAhyd8d1WHkW1narTfPwVyNN3cJV0EX8Dwf2fLHEnOINFL8FNvKWisAnei1QNirGxqr1mtB1FqL1Z6CD9L1xtqzzVotZOw0jnZnHPaWNDN8myWJ6kaaKBxsjTtNLJQBMfHPeZo8uAHTtgJntBv/uFyeW4oaIe1MFCVkeFoTEkAe+v8kCFVWQPCLuR8MPxhL4Png2RDENVYmmNHdgr3lC6FJPt/cuCgVYb6fI8drCBKE3AByEBwbIvVlGd4+Rh/CzBh0+1/eJxLWSKeejGHZ/3Uvt4rGxL6VAbQY86Z7b/oqtGLdW9Qw+hwipJ9Z6DXm09u28dOEQ3C4EO5dDb10vf3ATfCLRcmU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
