travis:
  secure:
    BINSTAR_TOKEN: UqFlv/V7tT8fOVhl+0PtQ7zWpEdJ0VqRQ8I/NtPhkAcpKIB4OsdblELRVMtWVz7+nG5Ul9Chv0e6qJeSanvaXUovOhNwd6IlSzt8PmEBZK45lBYD0JhU7KwhPPjKXsnu5IvbIklfvIHJ5uC7bXfV9UBqVFqKA5Y9MQkFyAlVkL1ffnd3IJ76hFau9H86qJPllxTtP9sh7jGS8SqT+wzOhWhWK5+z7RFQe1g3+U3T75y/qDKcz1IJTQ8i09OCLu6A8+QpaLqVOOjIi9X3H+I7RZh/kV18kmjJrBIiy8JSl1W4dbb8vnW2XPAbBK+3RgvZfwlsX/dJ6SIjNtpdF1Pg72VhyP6FNaxBMG5MwTDg7dIqnZUAxacfp4A3lFKxCqEXxDG7OfGBbAy/HVlw47QzSvV7gqD6kvFVFaXJRM+cfDZXjhToy41oCpw61qnmWhHs4Z8sH7p2tnNzwHmhBkkQ1XOswUMzSo16aHByH8vJEaYxoMpdlHqkKLNAkl3+S37KQvE/AnK3EnW/36I7W2c07CB638ZcTNyt6Ub+OdxItpj4rSRnd3ie4AxjOM8W/GmmglzKwNePzs30gBAEVPlQFa+3F0XtkWF4aw1Vi906bNv3TAVGm22w2MoX54DMNYGE5ZF5cvjIFlJOOo5XT+kEkXUIgamG4owreCbTBlx/LA0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
